In [113]:
import pandas as pd 
import numpy as np
from IPython.core.display import display, HTML

In [114]:
df = pd.read_csv('/Users/meganpolak/Downloads/2016.csv', names=('Year','Respondent_ID','Agency_Code','Loan_Type','Property_Type','Loan_Purpose','Occupancy','Loan_Amount','Preapproval','Action_Type','MSA-MD','State_Code','County_Code','Census_Tract_Number','Applicant_Ethnicity','Co_Applicant_Ethnicity','Applicant_Race_1','Applicant_Race_2','Applicant_Race_3','Applicant_Race_4','Applicant_Race_5','Co_Applicant_Race_1','Co_Applicant_Race_2','Co_Applicant_Race_3','Co_Applicant_Race_4','Co_Applicant_Race_5','Applicant_Sex','Co_Applicant_Sex','Applicant_Income','Purchaser_Type ','Denial_Reason_1','Denial_Reason_2','Denial_Reason_3','Rate_Spread','HOEPA_Status','Lien_Status','Edit_Status','Sequence_Number','Population','Minority_Population_%','FFIEC_Median_Family_Income','Tract_to_MSA/MD_Income_%','Number_of_Owner-occupied_units','Number_of_1-to_4-Family_units','Application_Date_Indicator'),header=None)

/Users/meganpolak/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (1,10,12,13,38,39,40,41,42,43) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [115]:
df.isnull().sum()

Year                                   0
Respondent_ID                          0
Agency_Code                            0
Loan_Type                              0
Property_Type                          0
Loan_Purpose                           0
Occupancy                              0
Loan_Amount                            0
Preapproval                            0
Action_Type                            0
MSA-MD                                 0
State_Code                        254571
County_Code                            0
Census_Tract_Number                    0
Applicant_Ethnicity                    0
Co_Applicant_Ethnicity                 0
Applicant_Race_1                       0
Applicant_Race_2                       0
Applicant_Race_3                       0
Applicant_Race_4                       0
Applicant_Race_5                       0
Co_Applicant_Race_1                    0
Co_Applicant_Race_2                    0
Co_Applicant_Race_3                    0
Co_Applicant_Race_4                    0
Co_Applicant_Race_5                    0
Applicant_Sex                          0
Co_Applicant_Sex                       0
Applicant_Income                       0
Purchaser_Type                         0
Denial_Reason_1                        0
Denial_Reason_2                        0
Denial_Reason_3                        0
Rate_Spread                            0
HOEPA_Status                           0
Lien_Status                            0
Edit_Status                            0
Sequence_Number                        0
Population                             0
Minority_Population_%                  0
FFIEC_Median_Family_Income             0
Tract_to_MSA/MD_Income_%               0
Number_of_Owner-occupied_units         0
Number_of_1-to_4-Family_units          0
Application_Date_Indicator             0
dtype: int64

In [116]:
# drop NA in state 

df=df.dropna(subset=['State_Code'])

In [117]:
df.isnull().sum()

Year                              0
Respondent_ID                     0
Agency_Code                       0
Loan_Type                         0
Property_Type                     0
Loan_Purpose                      0
Occupancy                         0
Loan_Amount                       0
Preapproval                       0
Action_Type                       0
MSA-MD                            0
State_Code                        0
County_Code                       0
Census_Tract_Number               0
Applicant_Ethnicity               0
Co_Applicant_Ethnicity            0
Applicant_Race_1                  0
Applicant_Race_2                  0
Applicant_Race_3                  0
Applicant_Race_4                  0
Applicant_Race_5                  0
Co_Applicant_Race_1               0
Co_Applicant_Race_2               0
Co_Applicant_Race_3               0
Co_Applicant_Race_4               0
Co_Applicant_Race_5               0
Applicant_Sex                     0
Co_Applicant_Sex                  0
Applicant_Income                  0
Purchaser_Type                    0
Denial_Reason_1                   0
Denial_Reason_2                   0
Denial_Reason_3                   0
Rate_Spread                       0
HOEPA_Status                      0
Lien_Status                       0
Edit_Status                       0
Sequence_Number                   0
Population                        0
Minority_Population_%             0
FFIEC_Median_Family_Income        0
Tract_to_MSA/MD_Income_%          0
Number_of_Owner-occupied_units    0
Number_of_1-to_4-Family_units     0
Application_Date_Indicator        0
dtype: int64

In [118]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 16078416 entries, 0 to 16078415
Data columns (total 45 columns):
Year                              int64
Respondent_ID                     object
Agency_Code                       int64
Loan_Type                         int64
Property_Type                     int64
Loan_Purpose                      int64
Occupancy                         int64
Loan_Amount                       int64
Preapproval                       int64
Action_Type                       int64
MSA-MD                            object
State_Code                        float64
County_Code                       object
Census_Tract_Number               object
Applicant_Ethnicity               int64
Co_Applicant_Ethnicity            int64
Applicant_Race_1                  int64
Applicant_Race_2                  object
Applicant_Race_3                  object
Applicant_Race_4                  object
Applicant_Race_5                  object
Co_Applicant_Race_1               int64
Co_Applicant_Race_2               object
Co_Applicant_Race_3               object
Co_Applicant_Race_4               object
Co_Applicant_Race_5               object
Applicant_Sex                     int64
Co_Applicant_Sex                  int64
Applicant_Income                  object
Purchaser_Type                    int64
Denial_Reason_1                   object
Denial_Reason_2                   object
Denial_Reason_3                   object
Rate_Spread                       object
HOEPA_Status                      int64
Lien_Status                       int64
Edit_Status                       object
Sequence_Number                   int64
Population                        object
Minority_Population_%             object
FFIEC_Median_Family_Income        object
Tract_to_MSA/MD_Income_%          object
Number_of_Owner-occupied_units    object
Number_of_1-to_4-Family_units     object
Application_Date_Indicator        int64
dtypes: float64(1), int64(20), object(24)
memory usage: 5.5+ GB

In [119]:
interested = ['Year', 'Respondent_ID', 'Agency_Code', 'Loan_Type', 'Property_Type','Loan_Purpose','Occupancy', 'Loan_Amount', 'Action_Type', 'State_Code', 'County_Code','Applicant_Income', 'Purchaser_Type ','Denial_Reason_1', 'Application_Date_Indicator']
df = df[interested]

In [120]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 16078416 entries, 0 to 16078415
Data columns (total 15 columns):
Year                          int64
Respondent_ID                 object
Agency_Code                   int64
Loan_Type                     int64
Property_Type                 int64
Loan_Purpose                  int64
Occupancy                     int64
Loan_Amount                   int64
Action_Type                   int64
State_Code                    float64
County_Code                   object
Applicant_Income              object
Purchaser_Type                int64
Denial_Reason_1               object
Application_Date_Indicator    int64
dtypes: float64(1), int64(10), object(4)
memory usage: 1.9+ GB

In [121]:

df['Applicant_Income'] = pd.to_numeric(df['Applicant_Income'].str.replace(' ',''), errors='force')

In [122]:

df['County_Code'] = pd.to_numeric(df['County_Code'].str.replace(' ',''), errors='force')

In [123]:
df.isnull().sum()

Year                                 0
Respondent_ID                        0
Agency_Code                          0
Loan_Type                            0
Property_Type                        0
Loan_Purpose                         0
Occupancy                            0
Loan_Amount                          0
Action_Type                          0
State_Code                           0
County_Code                   13687433
Applicant_Income               2474078
Purchaser_Type                       0
Denial_Reason_1                      0
Application_Date_Indicator           0
dtype: int64

In [124]:
df=df.dropna(subset=['County_Code'])

In [125]:

# replace missing values with mean 
df['Applicant_Income'].fillna(df['Applicant_Income'].mean(), inplace = True)

In [126]:
df.isnull().sum()

Year                          0
Respondent_ID                 0
Agency_Code                   0
Loan_Type                     0
Property_Type                 0
Loan_Purpose                  0
Occupancy                     0
Loan_Amount                   0
Action_Type                   0
State_Code                    0
County_Code                   0
Applicant_Income              0
Purchaser_Type                0
Denial_Reason_1               0
Application_Date_Indicator    0
dtype: int64

In [127]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2390983 entries, 16384 to 16078415
Data columns (total 15 columns):
Year                          int64
Respondent_ID                 object
Agency_Code                   int64
Loan_Type                     int64
Property_Type                 int64
Loan_Purpose                  int64
Occupancy                     int64
Loan_Amount                   int64
Action_Type                   int64
State_Code                    float64
County_Code                   float64
Applicant_Income              float64
Purchaser_Type                int64
Denial_Reason_1               object
Application_Date_Indicator    int64
dtypes: float64(3), int64(10), object(2)
memory usage: 291.9+ MB

In [128]:
cols1=['State_Code','County_Code','Applicant_Income']

In [129]:
df[cols1]=df[cols1].applymap(np.int64)

In [130]:
# load state codes data 
state= pd.read_csv('/Users/meganpolak/Downloads/StateCodes.csv', sep=',', engine='python')
state

                    Name  FIPS State Numeric Code Official�USPS Code
0                Alabama                        1                 AL
1                 Alaska                        2                 AK
2                Arizona                        4                 AZ
3               Arkansas                        5                 AR
4             California                        6                 CA
5               Colorado                        8                 CO
6            Connecticut                        9                 CT
7               Delaware                       10                 DE
8   District of Columbia                       11                 DC
9                Florida                       12                 FL
10               Georgia                       13                 GA
11                Hawaii                       15                 HI
12                 Idaho                       16                 ID
13              Illinois                       17                 IL
14               Indiana                       18                 IN
15                  Iowa                       19                 IA
16                Kansas                       20                 KS
17              Kentucky                       21                 KY
18             Louisiana                       22                 LA
19                 Maine                       23                 ME
20              Maryland                       24                 MD
21         Massachusetts                       25                 MA
22              Michigan                       26                 MI
23             Minnesota                       27                 MN
24           Mississippi                       28                 MS
25              Missouri                       29                 MO
26               Montana                       30                 MT
27              Nebraska                       31                 NE
28                Nevada                       32                 NV
29         New Hampshire                       33                 NH
30            New Jersey                       34                 NJ
31            New Mexico                       35                 NM
32              New York                       36                 NY
33        North Carolina                       37                 NC
34          North Dakota                       38                 ND
35                  Ohio                       39                 OH
36              Oklahoma                       40                 OK
37                Oregon                       41                 OR
38          Pennsylvania                       42                 PA
39          Rhode Island                       44                 RI
40        South Carolina                       45                 SC
41          South Dakota                       46                 SD
42             Tennessee                       47                 TN
43                 Texas                       48                 TX
44                  Utah                       49                 UT
45               Vermont                       50                 VT
46              Virginia                       51                 VA
47            Washington                       53                 WA
48         West Virginia                       54                 WV
49             Wisconsin                       55                 WI
50               Wyoming                       56                 WY
51                  Guam                       66                 GU
52           Puerto Rico                       72                 PR
53        Virgin Islands                       78                 VI

In [131]:
state= state.rename(columns={'FIPS State Numeric Code':'State_Code'})

In [132]:
df=df.merge(state,how='left')

In [133]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2390983 entries, 0 to 2390982
Data columns (total 17 columns):
Year                          int64
Respondent_ID                 object
Agency_Code                   int64
Loan_Type                     int64
Property_Type                 int64
Loan_Purpose                  int64
Occupancy                     int64
Loan_Amount                   int64
Action_Type                   int64
State_Code                    int64
County_Code                   int64
Applicant_Income              int64
Purchaser_Type                int64
Denial_Reason_1               object
Application_Date_Indicator    int64
Name                          object
Official�USPS Code            object
dtypes: int64(13), object(4)
memory usage: 328.4+ MB

In [135]:
df=df.rename(columns={'Name':'Property_Location','Official�USPS Code':'USPS_Code'})

In [136]:
df.isnull().sum()

Year                          0
Respondent_ID                 0
Agency_Code                   0
Loan_Type                     0
Property_Type                 0
Loan_Purpose                  0
Occupancy                     0
Loan_Amount                   0
Action_Type                   0
State_Code                    0
County_Code                   0
Applicant_Income              0
Purchaser_Type                0
Denial_Reason_1               0
Application_Date_Indicator    0
Property_Location             0
USPS_Code                     0
dtype: int64

In [137]:
df.shape

(2390983, 17)

In [138]:
gdp= pd.read_csv('/Users/meganpolak/Downloads/GDP_all_states.csv')

In [139]:
gdp.isnull().sum()

StateName                         0
Year                              0
Gross_State_Product_in_bilions    0
Real_State_Growth_%               0
dtype: int64

In [140]:
# rename 
gdp= gdp.rename(columns={'StateName':'Property_Location'})

In [141]:
new_df = pd.merge(df, gdp,  how='left', left_on=['Property_Location','Year'], right_on = ['Property_Location','Year'])

In [142]:
new_df.isnull().sum()

Year                              0
Respondent_ID                     0
Agency_Code                       0
Loan_Type                         0
Property_Type                     0
Loan_Purpose                      0
Occupancy                         0
Loan_Amount                       0
Action_Type                       0
State_Code                        0
County_Code                       0
Applicant_Income                  0
Purchaser_Type                    0
Denial_Reason_1                   0
Application_Date_Indicator        0
Property_Location                 0
USPS_Code                         0
Gross_State_Product_in_bilions    0
Real_State_Growth_%               0
dtype: int64

In [143]:
# load intrest rate data per year 
intRate=pd.read_csv('/Users/meganpolak/Desktop/InterestRateByYear.csv')

In [144]:
intRate = intRate[['Year', 'US_30_yr_FRM']]
intRate

   Year  US_30_yr_FRM
0  2010      4.689808
1  2011      4.447885
2  2012      3.657500
3  2013      3.975577
4  2014      4.168868
5  2015      3.850577
6  2016      3.654038
7  2017      3.989808

In [145]:
# merge data on Year 
new_df = pd.merge(new_df,intRate, how='left', left_on=['Year'], right_on = ['Year'])

In [146]:
# caluclate PMT for 30 years 
new_df['PMT_30yr']=-np.pmt((new_df.US_30_yr_FRM/100)/12,360,new_df.Loan_Amount*1000)

In [147]:
# calculate DTI for 30 15 and 5 years 

new_df['DTI_30yr']= new_df.PMT_30yr/(new_df.Applicant_Income/12)

In [148]:
new_df.columns

Index(['Year', 'Respondent_ID', 'Agency_Code', 'Loan_Type', 'Property_Type',
       'Loan_Purpose', 'Occupancy', 'Loan_Amount', 'Action_Type', 'State_Code',
       'County_Code', 'Applicant_Income', 'Purchaser_Type ', 'Denial_Reason_1',
       'Application_Date_Indicator', 'Property_Location', 'USPS_Code',
       'Gross_State_Product_in_bilions', 'Real_State_Growth_%', 'US_30_yr_FRM',
       'PMT_30yr', 'DTI_30yr'],
      dtype='object')

In [150]:
new_df['Gross_State_Product_in_bilions'] = new_df.Gross_State_Product_in_bilions.str.replace(r'\s+','').astype(float)
#new_df['Gross State Product(in billions)'] = pd.to(new_df['Gross State Product(in billions)'].str.replace(' ',''), errors='force')

In [151]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2390983 entries, 0 to 2390982
Data columns (total 22 columns):
Year                              int64
Respondent_ID                     object
Agency_Code                       int64
Loan_Type                         int64
Property_Type                     int64
Loan_Purpose                      int64
Occupancy                         int64
Loan_Amount                       int64
Action_Type                       int64
State_Code                        int64
County_Code                       int64
Applicant_Income                  int64
Purchaser_Type                    int64
Denial_Reason_1                   object
Application_Date_Indicator        int64
Property_Location                 object
USPS_Code                         object
Gross_State_Product_in_bilions    float64
Real_State_Growth_%               float64
US_30_yr_FRM                      float64
PMT_30yr                          float64
DTI_30yr                          float64
dtypes: float64(5), int64(13), object(4)
memory usage: 419.6+ MB

In [152]:
new_df.isnull().sum()

Year                              0
Respondent_ID                     0
Agency_Code                       0
Loan_Type                         0
Property_Type                     0
Loan_Purpose                      0
Occupancy                         0
Loan_Amount                       0
Action_Type                       0
State_Code                        0
County_Code                       0
Applicant_Income                  0
Purchaser_Type                    0
Denial_Reason_1                   0
Application_Date_Indicator        0
Property_Location                 0
USPS_Code                         0
Gross_State_Product_in_bilions    0
Real_State_Growth_%               0
US_30_yr_FRM                      0
PMT_30yr                          0
DTI_30yr                          0
dtype: int64

In [153]:
# load unemployment rate per state and year 
Unemploy=pd.read_csv('/Users/meganpolak/Documents/Unemp.csv')

In [154]:
# rename state col to property location 
Unemploy=Unemploy.rename(columns={'State':'Property_Location'})

In [155]:
# add unemployment rate to the df 
new_df = pd.merge(new_df,Unemploy,  how='left', left_on=['Property_Location','Year'], right_on = ['Property_Location','Year'])

In [156]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2390983 entries, 0 to 2390982
Data columns (total 23 columns):
Year                              int64
Respondent_ID                     object
Agency_Code                       int64
Loan_Type                         int64
Property_Type                     int64
Loan_Purpose                      int64
Occupancy                         int64
Loan_Amount                       int64
Action_Type                       int64
State_Code                        int64
County_Code                       int64
Applicant_Income                  int64
Purchaser_Type                    int64
Denial_Reason_1                   object
Application_Date_Indicator        int64
Property_Location                 object
USPS_Code                         object
Gross_State_Product_in_bilions    float64
Real_State_Growth_%               float64
US_30_yr_FRM                      float64
PMT_30yr                          float64
DTI_30yr                          float64
Unemployemnt                      float64
dtypes: float64(6), int64(13), object(4)
memory usage: 437.8+ MB

In [157]:
new_df

,Year,Respondent_ID,Agency_Code,Loan_Type,Property_Type,Loan_Purpose,Occupancy,Loan_Amount,Action_Type,State_Code,...,Denial_Reason_1,Application_Date_Indicator,Property_Location,USPS_Code,Gross_State_Product_in_bilions,Real_State_Growth_%,US_30_yr_FRM,PMT_30yr,DTI_30yr,Unemployemnt
0,2016,26-0021318,7,1,1,3,1,231,3,2,...,,0,Alaska,AK,50.7,-5.0,3.654038,1057.257582,154.720622,6.9
1,2016,26-0021318,7,1,1,3,1,199,3,2,...,,0,Alaska,AK,50.7,-5.0,3.654038,910.797657,248.399361,6.9
2,2016,26-0021318,7,3,1,3,1,411,1,2,...,,0,Alaska,AK,50.7,-5.0,3.654038,1881.094659,118.805978,6.9
3,2016,26-0021318,7,2,1,3,1,239,3,2,...,,0,Alaska,AK,50.7,-5.0,3.654038,1093.872563,218.774513,6.9
4,2016,26-0021318,7,1,1,2,1,280,4,2,...,,0,Alaska,AK,50.7,-5.0,3.654038,1281.524342,161.876759,6.9
5,2016,26-0021318,7,3,1,2,1,174,3,2,...,,0,Alaska,AK,50.7,-5.0,3.654038,796.375841,62.460850,6.9
6,2016,26-0021318,7,1,1,2,2,214,3,2,...,,0,Alaska,AK,50.7,-5.0,3.654038,979.450747,158.829851,6.9
7,2016,26-0021318,7,1,1,3,1,250,1,2,...,,0,Alaska,AK,50.7,-5.0,3.654038,1144.218163,116.361169,6.9
8,2016,26-0021318,7,1,1,3,1,265,3,2,...,,0,Alaska,AK,50.7,-5.0,3.654038,1212.871252,82.228559,6.9
9,2016,26-0021318,7,1,1,3,1,280,3,2,...,,0,Alaska,AK,50.7,-5.0,3.654038,1281.524342,97.330963,6.9
10,2016,26-0423240,7,2,1,3,1,210,3,2,...,3,0,Alaska,AK,50.7,-5.0,3.654038,961.143257,128.152434,6.9
11,2016,26-0595342,7,2,1,1,1,231,1,2,...,,0,Alaska,AK,50.7,-5.0,3.654038,1057.257582,133.548326,6.9
12,2016,26-0595342,7,1,1,3,1,246,3,2,...,7,0,Alaska,AK,50.7,-5.0,3.654038,1125.910672,386.026516,6.9
13,2016,26-0595342,7,1,1,1,1,218,1,2,...,,0,Alaska,AK,50.7,-5.0,3.654038,997.758238,193.114498,6.9
14,2016,26-0595342,7,2,1,1,1,137,1,2,...,,0,Alaska,AK,50.7,-5.0,3.654038,627.031553,242.721892,6.9
15,2016,26-0595342,7,1,1,1,1,208,1,2,...,,0,Alaska,AK,50.7,-5.0,3.654038,951.989511,207.706802,6.9
16,2016,26-0595342,7,1,1,1,1,157,1,2,...,,0,Alaska,AK,50.7,-5.0,3.654038,718.569006,153.979073,6.9
17,2016,26-0595342,7,2,1,1,1,287,1,2,...,,0,Alaska,AK,50.7,-5.0,3.654038,1313.562451,185.444111,6.9
18,2016,26-0595342,7,4,1,1,1,182,1,2,...,,0,Alaska,AK,50.7,-5.0,3.654038,832.990822,195.997841,6.9
19,2016,26-0595342,7,4,1,1,1,183,3,2,...,9,0,Alaska,AK,50.7,-5.0,3.654038,837.567695,218.495920,6.9
20,2016,26-0595342,7,3,1,1,1,559,2,2,...,,0,Alaska,AK,50.7,-5.0,3.654038,2558.471811,361.196020,6.9
21,2016,26-0595342,7,2,1,1,1,126,1,2,...,,0,Alaska,AK,50.7,-5.0,3.654038,576.685954,314.555975,6.9
22,2016,26-0595342,7,2,1,1,1,299,1,2,...,,0,Alaska,AK,50.7,-5.0,3.654038,1368.484922,283.134812,6.9
23,2016,26-0595342,7,1,1,1,1,227,1,2,...,,0,Alaska,AK,50.7,-5.0,3.654038,1038.950092,135.515229,6.9
24,2016,26-0595342,7,2,1,1,1,206,1,2,...,,0,Alaska,AK,50.7,-5.0,3.654038,942.835766,240.724025,6.9
25,2016,26-0595342,7,1,1,1,1,232,1,2,...,,0,Alaska,AK,50.7,-5.0,3.654038,1061.834455,157.308808,6.9
26,2016,26-0595342,7,2,1,1,1,245,3,2,...,3,0,Alaska,AK,50.7,-5.0,3.654038,1121.333799,162.120549,6.9
27,2016,26-0595342,7,2,1,1,1,245,1,2,...,,0,Alaska,AK,50.7,-5.0,3.654038,1121.333799,152.909154,6.9
28,2016,26-0595342,7,2,1,1,1,137,1,2,...,,0,Alaska,AK,50.7,-5.0,3.654038,627.031553,51.892266,6.9
29,2016,26-0595342,7,1,1,3,1,183,1,2,...,,0,Alaska,AK,50.7,-5.0,3.654038,837.567695,61.285441,6.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2390953,2016,95-4762204,7,1,1,3,1,170,1,51,...,,0,Virginia,VA,494.3,0.6,3.654038,778.068351,57.281106,4.1
2390954,2016,95-4762204,7,1,1,3,2,220,4,51,...,,0,Virginia,VA,494.3,0.6,3.654038,1006.911983,83.909332,4.1
2390955,2016,95-4866828,7,3,1,3,1,1006,1,51,...,,0,Virginia,VA,494.3,0.6,3.654038,4604.333886,613.911185,4.1
2390956,2016,95-4866828,7,3,1,3,1,255,1,51,...,,0,Virginia,VA,494.3,0.6,3.654038,1167.102526,155.613670,4.1
2390957,2016,95-4866828,7,2,1,1,1,249,2,51,...,,0,Virginia,VA,494.3,0.6,3.654038,1139.641290,115.895724,4.1
2390958,2016,95-4866828,7,2,1,1,1,231,1,51,...,,0,Virginia,VA,494.3,0.6,3.654038,1057.257582,144.171488,4.1
2390959,2016,95-4866828,7,2,1,2,1,86,1,51,...,,0,Virginia,VA,494.3,0.6,3.654038,393.611048,314.888838,4.1
2390960,2016,95-4866828,7,2,1,3,1,237,1,51,...,,0,Virginia,VA,494.3,0.6,3.654038,1084.718818,144.629176,4.1
2390961,2016,95-4866828,7,1,1,3,1,163,1,51,...,,0,Virginia,VA,494.3,0.6,3.654038,746.030242,127.890899,4.1
2390962,2016,95-4866828,7,2,1,3,1,136,1,51,...,,0,Virginia,VA,494.3,0.6,3.654038,622.454680,82.993957,4.1
2390963,2016,95-4866828,7,2,1,3,1,279,1,51,...,,0,Virginia,VA,494.3,0.6,3.654038,1276.947469,170.259663,4.1
2390964,2016,95-4866828,7,1,1,3,1,118,4,51,...,,0,Virginia,VA,494.3,0.6,3.654038,540.070973,135.017743,4.1
2390965,2016,95-4866828,7,2,2,3,1,165,1,51,...,,0,Virginia,VA,494.3,0.6,3.654038,755.183987,100.691198,4.1
2390966,2016,95-4866828,7,2,1,1,1,186,5,51,...,,0,Virginia,VA,494.3,0.6,3.654038,851.298313,98.226728,4.1
2390967,2016,95-4866828,7,3,1,3,1,193,2,51,...,,0,Virginia,VA,494.3,0.6,3.654038,883.336421,117.778190,4.1
2390968,2016,95-4866828,7,1,1,3,1,164,1,51,...,,0,Virginia,VA,494.3,0.6,3.654038,750.607115,180.145708,4.1
2390969,2016,95-4866828,7,2,1,2,1,157,1,51,...,,0,Virginia,VA,494.3,0.6,3.654038,718.569006,151.277685,4.1
2390970,2016,95-4866828,7,3,1,1,1,260,1,51,...,,0,Virginia,VA,494.3,0.6,3.654038,1189.986889,201.124545,4.1
2390971,2016,95-4866828,7,1,1,3,1,268,4,51,...,,0,Virginia,VA,494.3,0.6,3.654038,1226.601870,229.987851,4.1
2390972,2016,95-4866828,7,3,1,3,2,172,4,51,...,,0,Virginia,VA,494.3,0.6,3.654038,787.222096,104.962946,4.1
2390973,2016,95-4866828,7,3,1,3,1,300,1,51,...,,0,Virginia,VA,494.3,0.6,3.654038,1373.061795,183.074906,4.1
2390974,2016,95-4866828,7,3,1,3,1,369,1,51,...,,0,Virginia,VA,494.3,0.6,3.654038,1688.866008,225.182134,4.1
2390975,2016,95-4866828,7,2,1,3,1,201,1,51,...,,0,Virginia,VA,494.3,0.6,3.654038,919.951403,122.660187,4.1
2390976,2016,95-4866828,7,3,1,3,1,221,1,51,...,,0,Virginia,VA,494.3,0.6,3.654038,1011.488856,134.865181,4.1
2390977,2016,95-4866828,7,2,1,1,1,157,5,51,...,,0,Virginia,VA,494.3,0.6,3.654038,718.569006,246.366516,4.1
2390978,2016,95-4866828,7,2,1,1,1,157,1,51,...,,0,Virginia,VA,494.3,0.6,3.654038,718.569006,221.098156,4.1
2390979,2016,95-4866828,7,1,1,1,1,152,2,51,...,,0,Virginia,VA,494.3,0.6,3.654038,695.684643,269.297281,4.1
2390980,2016,99-0005356,9,1,1,2,2,50,1,51,...,,0,Virginia,VA,494.3,0.6,3.654038,228.843633,13.395725,4.1
2390981,2016,99-0035093,1,1,1,1,1,105,2,51,...,,0,Virginia,VA,494.3,0.6,3.654038,480.571628,117.691011,4.1
2390982,2016,99-0703835,3,1,1,1,1,45,3,51,...,,0,Virginia,VA,494.3,0.6,3.654038,205.959269,54.922472,4.1

In [158]:
new_df=new_df.rename(columns={'US_30_yr_FRM':'Rate','PMT_30yr':'PMT','DTI_30yr':'IncRat', 'Gross_State_Product_in_bilions':'GDP', 'Applicant_Income':'Income', 'Loan_Amount':'Amount'})
new_df["AmorTerm"] = 360

In [174]:
def conditions(s):
    if (s['Denial_Reason_1'] == '3'):
        return 1
    else:
         return 4

In [175]:
new_df['BoCreditScor'] = df.apply(conditions, axis=1)

In [176]:
def conditions(s):
    if (s['Denial_Reason_1'] == '8'):
        return 1
    else:
         return 0.75

In [177]:
new_df['LTV'] = df.apply(conditions, axis=1)

In [179]:
new_df.isnull().sum()

Year                          0
Respondent_ID                 0
Agency_Code                   0
Loan_Type                     0
Property_Type                 0
Loan_Purpose                  0
Occupancy                     0
Amount                        0
Action_Type                   0
State_Code                    0
County_Code                   0
Income                        0
Purchaser_Type                0
Denial_Reason_1               0
Application_Date_Indicator    0
Property_Location             0
USPS_Code                     0
GDP                           0
Real_State_Growth_%           0
Rate                          0
PMT                           0
IncRat                        0
Unemployemnt                  0
AmorTerm                      0
LTV                           0
BoCreditScor                  0
dtype: int64

In [182]:
new_df

,Year,Respondent_ID,Agency_Code,Loan_Type,Property_Type,Loan_Purpose,Occupancy,Amount,Action_Type,State_Code,...,USPS_Code,GDP,Real_State_Growth_%,Rate,PMT,IncRat,Unemployemnt,AmorTerm,LTV,BoCreditScor
0,2016,26-0021318,7,1,1,3,1,231,3,2,...,AK,50.7,-5.0,3.654038,1057.257582,154.720622,6.9,360,0.75,4
1,2016,26-0021318,7,1,1,3,1,199,3,2,...,AK,50.7,-5.0,3.654038,910.797657,248.399361,6.9,360,0.75,4
2,2016,26-0021318,7,3,1,3,1,411,1,2,...,AK,50.7,-5.0,3.654038,1881.094659,118.805978,6.9,360,0.75,4
3,2016,26-0021318,7,2,1,3,1,239,3,2,...,AK,50.7,-5.0,3.654038,1093.872563,218.774513,6.9,360,0.75,4
4,2016,26-0021318,7,1,1,2,1,280,4,2,...,AK,50.7,-5.0,3.654038,1281.524342,161.876759,6.9,360,0.75,4
5,2016,26-0021318,7,3,1,2,1,174,3,2,...,AK,50.7,-5.0,3.654038,796.375841,62.460850,6.9,360,0.75,4
6,2016,26-0021318,7,1,1,2,2,214,3,2,...,AK,50.7,-5.0,3.654038,979.450747,158.829851,6.9,360,0.75,4
7,2016,26-0021318,7,1,1,3,1,250,1,2,...,AK,50.7,-5.0,3.654038,1144.218163,116.361169,6.9,360,0.75,4
8,2016,26-0021318,7,1,1,3,1,265,3,2,...,AK,50.7,-5.0,3.654038,1212.871252,82.228559,6.9,360,0.75,4
9,2016,26-0021318,7,1,1,3,1,280,3,2,...,AK,50.7,-5.0,3.654038,1281.524342,97.330963,6.9,360,0.75,4
10,2016,26-0423240,7,2,1,3,1,210,3,2,...,AK,50.7,-5.0,3.654038,961.143257,128.152434,6.9,360,0.75,1
11,2016,26-0595342,7,2,1,1,1,231,1,2,...,AK,50.7,-5.0,3.654038,1057.257582,133.548326,6.9,360,0.75,4
12,2016,26-0595342,7,1,1,3,1,246,3,2,...,AK,50.7,-5.0,3.654038,1125.910672,386.026516,6.9,360,0.75,4
13,2016,26-0595342,7,1,1,1,1,218,1,2,...,AK,50.7,-5.0,3.654038,997.758238,193.114498,6.9,360,0.75,4
14,2016,26-0595342,7,2,1,1,1,137,1,2,...,AK,50.7,-5.0,3.654038,627.031553,242.721892,6.9,360,0.75,4
15,2016,26-0595342,7,1,1,1,1,208,1,2,...,AK,50.7,-5.0,3.654038,951.989511,207.706802,6.9,360,0.75,4
16,2016,26-0595342,7,1,1,1,1,157,1,2,...,AK,50.7,-5.0,3.654038,718.569006,153.979073,6.9,360,0.75,4
17,2016,26-0595342,7,2,1,1,1,287,1,2,...,AK,50.7,-5.0,3.654038,1313.562451,185.444111,6.9,360,0.75,4
18,2016,26-0595342,7,4,1,1,1,182,1,2,...,AK,50.7,-5.0,3.654038,832.990822,195.997841,6.9,360,0.75,4
19,2016,26-0595342,7,4,1,1,1,183,3,2,...,AK,50.7,-5.0,3.654038,837.567695,218.495920,6.9,360,0.75,4
20,2016,26-0595342,7,3,1,1,1,559,2,2,...,AK,50.7,-5.0,3.654038,2558.471811,361.196020,6.9,360,0.75,4
21,2016,26-0595342,7,2,1,1,1,126,1,2,...,AK,50.7,-5.0,3.654038,576.685954,314.555975,6.9,360,0.75,4
22,2016,26-0595342,7,2,1,1,1,299,1,2,...,AK,50.7,-5.0,3.654038,1368.484922,283.134812,6.9,360,0.75,4
23,2016,26-0595342,7,1,1,1,1,227,1,2,...,AK,50.7,-5.0,3.654038,1038.950092,135.515229,6.9,360,0.75,4
24,2016,26-0595342,7,2,1,1,1,206,1,2,...,AK,50.7,-5.0,3.654038,942.835766,240.724025,6.9,360,0.75,4
25,2016,26-0595342,7,1,1,1,1,232,1,2,...,AK,50.7,-5.0,3.654038,1061.834455,157.308808,6.9,360,0.75,4
26,2016,26-0595342,7,2,1,1,1,245,3,2,...,AK,50.7,-5.0,3.654038,1121.333799,162.120549,6.9,360,0.75,1
27,2016,26-0595342,7,2,1,1,1,245,1,2,...,AK,50.7,-5.0,3.654038,1121.333799,152.909154,6.9,360,0.75,4
28,2016,26-0595342,7,2,1,1,1,137,1,2,...,AK,50.7,-5.0,3.654038,627.031553,51.892266,6.9,360,0.75,4
29,2016,26-0595342,7,1,1,3,1,183,1,2,...,AK,50.7,-5.0,3.654038,837.567695,61.285441,6.9,360,0.75,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2390953,2016,95-4762204,7,1,1,3,1,170,1,51,...,VA,494.3,0.6,3.654038,778.068351,57.281106,4.1,360,0.75,4
2390954,2016,95-4762204,7,1,1,3,2,220,4,51,...,VA,494.3,0.6,3.654038,1006.911983,83.909332,4.1,360,0.75,4
2390955,2016,95-4866828,7,3,1,3,1,1006,1,51,...,VA,494.3,0.6,3.654038,4604.333886,613.911185,4.1,360,0.75,4
2390956,2016,95-4866828,7,3,1,3,1,255,1,51,...,VA,494.3,0.6,3.654038,1167.102526,155.613670,4.1,360,0.75,4
2390957,2016,95-4866828,7,2,1,1,1,249,2,51,...,VA,494.3,0.6,3.654038,1139.641290,115.895724,4.1,360,0.75,4
2390958,2016,95-4866828,7,2,1,1,1,231,1,51,...,VA,494.3,0.6,3.654038,1057.257582,144.171488,4.1,360,0.75,4
2390959,2016,95-4866828,7,2,1,2,1,86,1,51,...,VA,494.3,0.6,3.654038,393.611048,314.888838,4.1,360,0.75,4
2390960,2016,95-4866828,7,2,1,3,1,237,1,51,...,VA,494.3,0.6,3.654038,1084.718818,144.629176,4.1,360,0.75,4
2390961,2016,95-4866828,7,1,1,3,1,163,1,51,...,VA,494.3,0.6,3.654038,746.030242,127.890899,4.1,360,0.75,4
2390962,2016,95-4866828,7,2,1,3,1,136,1,51,...,VA,494.3,0.6,3.654038,622.454680,82.993957,4.1,360,0.75,4
2390963,2016,95-4866828,7,2,1,3,1,279,1,51,...,VA,494.3,0.6,3.654038,1276.947469,170.259663,4.1,360,0.75,4
2390964,2016,95-4866828,7,1,1,3,1,118,4,51,...,VA,494.3,0.6,3.654038,540.070973,135.017743,4.1,360,0.75,4
2390965,2016,95-4866828,7,2,2,3,1,165,1,51,...,VA,494.3,0.6,3.654038,755.183987,100.691198,4.1,360,0.75,4
2390966,2016,95-4866828,7,2,1,1,1,186,5,51,...,VA,494.3,0.6,3.654038,851.298313,98.226728,4.1,360,0.75,4
2390967,2016,95-4866828,7,3,1,3,1,193,2,51,...,VA,494.3,0.6,3.654038,883.336421,117.778190,4.1,360,0.75,4
2390968,2016,95-4866828,7,1,1,3,1,164,1,51,...,VA,494.3,0.6,3.654038,750.607115,180.145708,4.1,360,0.75,4
2390969,2016,95-4866828,7,2,1,2,1,157,1,51,...,VA,494.3,0.6,3.654038,718.569006,151.277685,4.1,360,0.75,4
2390970,2016,95-4866828,7,3,1,1,1,260,1,51,...,VA,494.3,0.6,3.654038,1189.986889,201.124545,4.1,360,0.75,4
2390971,2016,95-4866828,7,1,1,3,1,268,4,51,...,VA,494.3,0.6,3.654038,1226.601870,229.987851,4.1,360,0.75,4
2390972,2016,95-4866828,7,3,1,3,2,172,4,51,...,VA,494.3,0.6,3.654038,787.222096,104.962946,4.1,360,0.75,4
2390973,2016,95-4866828,7,3,1,3,1,300,1,51,...,VA,494.3,0.6,3.654038,1373.061795,183.074906,4.1,360,0.75,4
2390974,2016,95-4866828,7,3,1,3,1,369,1,51,...,VA,494.3,0.6,3.654038,1688.866008,225.182134,4.1,360,0.75,4
2390975,2016,95-4866828,7,2,1,3,1,201,1,51,...,VA,494.3,0.6,3.654038,919.951403,122.660187,4.1,360,0.75,4
2390976,2016,95-4866828,7,3,1,3,1,221,1,51,...,VA,494.3,0.6,3.654038,1011.488856,134.865181,4.1,360,0.75,4
2390977,2016,95-4866828,7,2,1,1,1,157,5,51,...,VA,494.3,0.6,3.654038,718.569006,246.366516,4.1,360,0.75,4
2390978,2016,95-4866828,7,2,1,1,1,157,1,51,...,VA,494.3,0.6,3.654038,718.569006,221.098156,4.1,360,0.75,4
2390979,2016,95-4866828,7,1,1,1,1,152,2,51,...,VA,494.3,0.6,3.654038,695.684643,269.297281,4.1,360,0.75,4
2390980,2016,99-0005356,9,1,1,2,2,50,1,51,...,VA,494.3,0.6,3.654038,228.843633,13.395725,4.1,360,0.75,4
2390981,2016,99-0035093,1,1,1,1,1,105,2,51,...,VA,494.3,0.6,3.654038,480.571628,117.691011,4.1,360,0.75,4
2390982,2016,99-0703835,3,1,1,1,1,45,3,51,...,VA,494.3,0.6,3.654038,205.959269,54.922472,4.1,360,0.75,4

In [181]:
new_df.to_csv('/Users/meganpolak/Documents/2016_Declined.csv')